//	Copyright © 2013 - 2014, Alain Metge. All rights reserved.
//
//		This file is part of Hyperstore (http://www.hyperstore.org)
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
// 
//     http://www.apache.org/licenses/LICENSE-2.0
// 
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
 
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hyperstore.Modeling {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ExceptionMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Hyperstore.Modeling.ExceptionMessages", typeof(ExceptionMessages).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already initialized.
        /// </summary>
        internal static string AlreadyInitialized {
            get {
                return ResourceManager.GetString("AlreadyInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Await in session is not allowed.
        /// </summary>
        internal static string AwaitInSessionIsNotAllowed {
            get {
                return ResourceManager.GetString("AwaitInSessionIsNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t create a nested session in a disposing session.
        /// </summary>
        internal static string CannotCreateNestedSessionInDisposingSession {
            get {
                return ResourceManager.GetString("CannotCreateNestedSessionInDisposingSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t set a category on an implicit constraint.
        /// </summary>
        internal static string CannotSetCategoryOnImplicitConstraint {
            get {
                return ResourceManager.GetString("CannotSetCategoryOnImplicitConstraint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t extend domain model. Graph adapter.
        /// </summary>
        internal static string CantExtendDomainModel_GraphAdapter {
            get {
                return ResourceManager.GetString("CantExtendDomainModel_GraphAdapter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t remove a schema element. Schema is immutable.
        /// </summary>
        internal static string CantRemoveSchemaElementSchemaIsImmutable {
            get {
                return ResourceManager.GetString("CantRemoveSchemaElementSchemaIsImmutable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t use an element from an unloaded domain.
        /// </summary>
        internal static string CantUseElementFromUnloadedDomain {
            get {
                return ResourceManager.GetString("CantUseElementFromUnloadedDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Composition already done.
        /// </summary>
        internal static string CompositionAlreadyDone {
            get {
                return ResourceManager.GetString("CompositionAlreadyDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create property {0} with id {1} for metaclass {2}.
        /// </summary>
        internal static string CreatePropertyWithIdForMetaclassFormat {
            get {
                return ResourceManager.GetString("CreatePropertyWithIdForMetaclassFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Critical error - Maybe because await in your session.
        /// </summary>
        internal static string CriticalErrorMaybeAwaitInSession {
            get {
                return ResourceManager.GetString("CriticalErrorMaybeAwaitInSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default configuration is null.
        /// </summary>
        internal static string DefaultConfigurationIsNull {
            get {
                return ResourceManager.GetString("DefaultConfigurationIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to services must inherit from DefaultDependencyResolver.
        /// </summary>
        internal static string Dependency_servicesMustInheritFromDefaultDependencyResolver {
            get {
                return ResourceManager.GetString("Dependency_servicesMustInheritFromDefaultDependencyResolver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application error.
        /// </summary>
        internal static string Diagnostic_ApplicationError {
            get {
                return ResourceManager.GetString("Diagnostic_ApplicationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command aborted.
        /// </summary>
        internal static string Diagnostic_CommandAborted {
            get {
                return ResourceManager.GetString("Diagnostic_CommandAborted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constraints process error.
        /// </summary>
        internal static string Diagnostic_ConstraintsProcessError {
            get {
                return ResourceManager.GetString("Diagnostic_ConstraintsProcessError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in persistence adapter.
        /// </summary>
        internal static string Diagnostic_ErrorInPersistenceAdapter {
            get {
                return ResourceManager.GetString("Diagnostic_ErrorInPersistenceAdapter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error when processing command {0}.
        /// </summary>
        internal static string Diagnostic_ErrorProcessingCommandFormat {
            get {
                return ResourceManager.GetString("Diagnostic_ErrorProcessingCommandFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error when processing after interceptor {0} for command {1}.
        /// </summary>
        internal static string Diagnostic_ErrorWhenProcessingAfterInterceptorforCommandFormat {
            get {
                return ResourceManager.GetString("Diagnostic_ErrorWhenProcessingAfterInterceptorforCommandFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error when processing before interceptor {0} for command {1}.
        /// </summary>
        internal static string Diagnostic_ErrorWhenProcessingBeforeInterceptorforCommandFormat {
            get {
                return ResourceManager.GetString("Diagnostic_ErrorWhenProcessingBeforeInterceptorforCommandFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error when processing error interceptor {0} for command {1}.
        /// </summary>
        internal static string Diagnostic_ErrorWhenProcessingErrorInterceptorforCommandFormat {
            get {
                return ResourceManager.GetString("Diagnostic_ErrorWhenProcessingErrorInterceptorforCommandFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domain model is read only - Can&apos;t create element {0}.
        /// </summary>
        internal static string DomainModelIsReadOnlyCantCreateElementFormat {
            get {
                return ResourceManager.GetString("DomainModelIsReadOnlyCantCreateElementFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domain name mismatch. Metadata {0} can&apos;t be added to metamodel {1}.
        /// </summary>
        internal static string DomainNameMismatchFormat {
            get {
                return ResourceManager.GetString("DomainNameMismatchFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate index {0}.
        /// </summary>
        internal static string DuplicateIndexFormat {
            get {
                return ResourceManager.GetString("DuplicateIndexFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate property name.
        /// </summary>
        internal static string DuplicatePropertyName {
            get {
                return ResourceManager.GetString("DuplicatePropertyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element must have a protected parameterless constructor.
        /// </summary>
        internal static string ElementMustHaveAProtectedParameterlessConstructor {
            get {
                return ResourceManager.GetString("ElementMustHaveAProtectedParameterlessConstructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EmptyStack.
        /// </summary>
        internal static string EmptyStack {
            get {
                return ResourceManager.GetString("EmptyStack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End element is not a valid element.
        /// </summary>
        internal static string EndElementIsNotAValidElement {
            get {
                return ResourceManager.GetString("EndElementIsNotAValidElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} exists but is not a schema element.
        /// </summary>
        internal static string ExistsButIsNotASchemaElementFormat {
            get {
                return ResourceManager.GetString("ExistsButIsNotASchemaElementFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} exists but is not a schema entity.
        /// </summary>
        internal static string ExistsButIsNotASchemaEntityFormat {
            get {
                return ResourceManager.GetString("ExistsButIsNotASchemaEntityFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extended domain not found.
        /// </summary>
        internal static string ExtendedDomainNotFound {
            get {
                return ResourceManager.GetString("ExtendedDomainNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatal error - Too many sessions.
        /// </summary>
        internal static string FatalErrorTooManySessions {
            get {
                return ResourceManager.GetString("FatalErrorTooManySessions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index insertion failed.
        /// </summary>
        internal static string IndexInsertionFailed {
            get {
                return ResourceManager.GetString("IndexInsertionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid class serialization.
        /// </summary>
        internal static string InvalidClassSerialization {
            get {
                return ResourceManager.GetString("InvalidClassSerialization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid domain name.
        /// </summary>
        internal static string InvalidDomainName {
            get {
                return ResourceManager.GetString("InvalidDomainName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid element {0}.
        /// </summary>
        internal static string InvalidElementFormat {
            get {
                return ResourceManager.GetString("InvalidElementFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid end type for this relationship.
        /// </summary>
        internal static string InvalidEndTypeForRelationship {
            get {
                return ResourceManager.GetString("InvalidEndTypeForRelationship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid identity format.
        /// </summary>
        internal static string InvalidIdentity {
            get {
                return ResourceManager.GetString("InvalidIdentity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid item type.
        /// </summary>
        internal static string InvalidItemType {
            get {
                return ResourceManager.GetString("InvalidItemType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid metaclass for reference.
        /// </summary>
        internal static string InvalidMetaclassForReference {
            get {
                return ResourceManager.GetString("InvalidMetaclassForReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid name : {0}.
        /// </summary>
        internal static string InvalidNameFormat {
            get {
                return ResourceManager.GetString("InvalidNameFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid property name. Can&apos;t be a property of IModelElement..
        /// </summary>
        internal static string InvalidPropertyNameCantBeAPropertyOfIModelElement {
            get {
                return ResourceManager.GetString("InvalidPropertyNameCantBeAPropertyOfIModelElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid reference.
        /// </summary>
        internal static string InvalidReference {
            get {
                return ResourceManager.GetString("InvalidReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid source type for this relationship.
        /// </summary>
        internal static string InvalidSourceTypeForRelationship {
            get {
                return ResourceManager.GetString("InvalidSourceTypeForRelationship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid value.
        /// </summary>
        internal static string InvalidValue {
            get {
                return ResourceManager.GetString("InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InvolvedModelElements are only avalaible when the session is being disposed. Use InvolvedElements instead..
        /// </summary>
        internal static string InvolvedModelElementsOnlyAvalaibleWhenSessionIsBeingDisposed {
            get {
                return ResourceManager.GetString("InvolvedModelElementsOnlyAvalaibleWhenSessionIsBeingDisposed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key doesn&apos;t exist {0}.
        /// </summary>
        internal static string KeyDoesntExistFormat {
            get {
                return ResourceManager.GetString("KeyDoesntExistFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock conflict on resource {0}.
        /// </summary>
        internal static string LockConflictOnResourceFormat {
            get {
                return ResourceManager.GetString("LockConflictOnResourceFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No schema found for this property. You must provide a schema for this property type. Only value types can be used to define a property. To create a relationship use SchemaRelationship.
        /// </summary>
        internal static string NoSchemaFoundForThisProperty {
            get {
                return ResourceManager.GetString("NoSchemaFoundForThisProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not found.
        /// </summary>
        internal static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only one-to-many or many-to-many relationships are allowed.
        /// </summary>
        internal static string OnlyOneToManyOrManyToManyAllowedRelationshipsAllowed {
            get {
                return ResourceManager.GetString("OnlyOneToManyOrManyToManyAllowedRelationshipsAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property name is not a valid property for metaclass {0}.
        /// </summary>
        internal static string PropertyNameNotValidForMetaclassFormat {
            get {
                return ResourceManager.GetString("PropertyNameNotValidForMetaclassFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReferenceHandler can&apos;t be used with a many-to-many relationship.
        /// </summary>
        internal static string ReferenceHandlerCantBeUsedWithManyToManyRelationship {
            get {
                return ResourceManager.GetString("ReferenceHandlerCantBeUsedWithManyToManyRelationship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ResolveAll works only with singleton.
        /// </summary>
        internal static string ResolveAllWorksOnlyWithSingleton {
            get {
                return ResourceManager.GetString("ResolveAllWorksOnlyWithSingleton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schema mismatch.
        /// </summary>
        internal static string SchemaMismatch {
            get {
                return ResourceManager.GetString("SchemaMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service {0} not found for domain {1}.
        /// </summary>
        internal static string ServiceNotFoundForDomainFormat {
            get {
                return ResourceManager.GetString("ServiceNotFoundForDomainFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start element is not a valid element.
        /// </summary>
        internal static string StartElementIsNotAValidElement {
            get {
                return ResourceManager.GetString("StartElementIsNotAValidElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatal error in the events notification process - {0}.
        /// </summary>
        internal static string Trace_FatalErrorInEventsNotificationProcessFormat {
            get {
                return ResourceManager.GetString("Trace_FatalErrorInEventsNotificationProcessFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try to load a duplicate domainModel {0}. Can happen when an active session blocks a domain unload.
        /// </summary>
        internal static string TryToLoadDuplicateDomainModelFormat {
            get {
                return ResourceManager.GetString("TryToLoadDuplicateDomainModelFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type factories must have the same behavior (singleton or not).
        /// </summary>
        internal static string TypeFactoriesMustHaveSameBehavior {
            get {
                return ResourceManager.GetString("TypeFactoriesMustHaveSameBehavior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type mismatch - End element must be a {0}.
        /// </summary>
        internal static string TypeMismatchEndElementMustBeAFormat {
            get {
                return ResourceManager.GetString("TypeMismatchEndElementMustBeAFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type mismatch - Start element must be a {0}.
        /// </summary>
        internal static string TypeMismatchStartElementMustBeAFormat {
            get {
                return ResourceManager.GetString("TypeMismatchStartElementMustBeAFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to create element of type {0}.
        /// </summary>
        internal static string UnableToCreateElementOfTypeFormat {
            get {
                return ResourceManager.GetString("UnableToCreateElementOfTypeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to create entity of type {0}. Must have a public constructor whith a IDomainModel parameter.
        /// </summary>
        internal static string UnableToCreateEntityOfTypeCtorWithIDomainModelRequiredFormat {
            get {
                return ResourceManager.GetString("UnableToCreateEntityOfTypeCtorWithIDomainModelRequiredFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to create relationship of type {0}. Must have a public constructor whith a start and end parameter.
        /// </summary>
        internal static string UnableToCreateRelationshipOfTypeRequiredCtorWithStartEndParametersFormat {
            get {
                return ResourceManager.GetString("UnableToCreateRelationshipOfTypeRequiredCtorWithStartEndParametersFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to register a service after a call to Resolve or ResolveAll.
        /// </summary>
        internal static string UnableToRegisterServiceAfterCallToResolveOrResolveAll {
            get {
                return ResourceManager.GetString("UnableToRegisterServiceAfterCallToResolveOrResolveAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown property {0} for element {1}.
        /// </summary>
        internal static string UnknownPropertyForElementFormat {
            get {
                return ResourceManager.GetString("UnknownPropertyForElementFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown property {0}.
        /// </summary>
        internal static string UnknownPropertyFormat {
            get {
                return ResourceManager.GetString("UnknownPropertyFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use RemoveRelationship to remove relationship.
        /// </summary>
        internal static string UseRemoveRelationshipToRemoveRelationship {
            get {
                return ResourceManager.GetString("UseRemoveRelationshipToRemoveRelationship", resourceCulture);
            }
        }
    }
}
